### ISSUE TITLE
Can't create a calendar

### ISSUE THREAD

**Issue by Bosmut** [VaiTon/unibocalendar#17] opened 2024-08-26 08:35 UTC
I was trying to create a calendar for next months for several curriculums: Laurea in Statistics (Maths&Stats), Laurea in Economics of Tourism and Cities (Curriculum Economics of tourism and Leisure industries).
There are 2 main issues:
1) There is no such curriculum (Economics of Tourism) not in unibo calendar tool, nor in original tool
2) It is impossible to create a calendar via unibocalendar for any program and curriculum, but it is possible to do it with original tool - I'd tried to make it for several different curriculums, not only mentioned above, and for any I hadn't got any good result. The final page with links to add created schedule in different apps was working, but if I would try to look at created calendar via button "Apri online" or add it to my google account, I always got the same plain calendar, without any lections added. 
I had check them several months ahead.

**Comment by samuelemusiani** [comment] 2024-09-07 08:49
Can you check if the second point is resolved after #16?

For the first point can you provide a link to the unibo website where you can find this curriculums that are not present in unibocalendar?

**Comment by Bosmut** [comment] 2024-09-07 11:57
It had actually started to work! But partually and unstable. I had checked this page (https://calendar.students.cs.unibo.it/courses/6054), and for both curriculums it was possible to create a schedule only for the first year, but not for the second. 
Also checked other courses - For Math&Stats it was working the same way (only creates a schedule for the first year).
When I tried to create a schedule for several different curriculums it stopped to work - rn I can't see a schedule of lections for any program, even those for which I've created it previously.

**Comment by samuelemusiani** [comment] 2024-09-07 14:51
This commmit (https://github.com/VaiTon/unibocalendar/pull/18/commits/3fbd7ef8e9204d310fe3de110d53b3cd029680e3) should fix your problem. It's in the #18 PR where I also added subject filtering, so it could take some time before merge

**Comment by Bosmut** [comment] 2024-09-07 20:41
Great, thank you! Will check it out when it will be merged with the main.

**Comment by Bosmut** [comment] 2024-09-08 12:58
So I've tested it more widely, and I think I've found the pattern.
If we create timetable for a program with single curriculum the tool works good (examples: https://calendar.students.cs.unibo.it/courses/8835, https://calendar.students.cs.unibo.it/courses/6061)
If there are more than 1 curriculum - it fails the creation of timetable (examples: https://calendar.students.cs.unibo.it/courses/9256, https://calendar.students.cs.unibo.it/courses/8850), but not always - for https://calendar.students.cs.unibo.it/courses/6054 it was able to create timetable for the first year, but not for the second or third.
I've checked, and for all examples above the schedule is published. 
The only differences I've seen is the need to choose the proper curriculum on the site of the program to display the schedule for it.

**Comment by samuelemusiani** [comment] 2024-09-11 19:04
Hi, we have merged #18. Can you test if it's working now? https://calendar.students.cs.unibo.it

**Comment by Bosmut** [comment] 2024-09-11 19:55
1) First thing - failed alingment of objects (buttons "Apri calendar", "Google Calendar | Apple Calendar") on a page, same issue at all pages:
![image](https://github.com/user-attachments/assets/0ceb7698-56ee-49d8-8c8f-9524acdc5876)
Seems reasonable to put the button with google/apple calendar under "Apri Calendar"
2) Checking/unchecking subjects for filtering change sizes of other objects on the page

But core functionality work well, I will test it more widely tomorrow.

btw I really like that the name of the program is now displayed in the google calendar app after adjustment, previously it was just a link

**Comment by samuelemusiani** [comment] 2024-09-12 14:42
1. What browser are you using? Because I have tested the new version in both Firefox and Chrome and I can't reproduce your screen. For me the filter menu - when opened - overlaps the other items on the page as expected. 
2. Checking/unchecking subjects add strings to the end of the URL. I wanted to make that visible to the user, so the buttons shift to the right. If you have a better idea for the UX I'm open to change the current implementation.

**Comment by Bosmut** [comment] 2024-09-13 11:41
1. Chrome Version 128.0.6613.137 (Official Build) (64-bit), but I bet the reason is screen size. I use a laptop with 14". Was able to reproduce that issue at a phone - and yeah, I've saw the new design, it fixed the issue for laptop view, but not for phone view. 
But I don't think it should be adopted to phone - It is highly unlikely that someone will use a phone to access the site, and even in that case - it is still possible to do everything, the bug is not blocking, so, I'd left it as is.
Btw, checked also with 10" tablet - and for a tablet all was fine.
2. Actually, I like the current design a lot already - the idea if hiding all subjects into drop-down menu works perfect for me.

Thanks a lot for fixing the issues!

**Comment by VaiTon** [comment] 2024-09-13 17:00
Thank you @Bosmut for reporting and @samuelemusiani for fixing! Can we close this?

**Comment by samuelemusiani** [comment] 2024-09-13 17:31
@Bosmut I've tried on the phone and on my 14" laptop but everything is working as expected. I can't reproduce your issue on the UI.

We can close this issue for me.

**Comment by Bosmut** [comment] 2024-09-16 19:46
Sure, this issue can be closed.

**Closed as completed** 2024-09-16 20:17 UTC
